const mongoose = require('mongoose');

const Expenseform = mongoose.model('Expenseform', {
   employeeCost: String,
   jan: String,
      feb:  String,
      march: String,
      april: String,
      may:  String,
      june: String,
      july:  String,
      aug:  String,
      sep:  String,
      oct: String,
      nov:  String,
      dec:  String,
    officeCost:  String,
    officejan:  String,
    officefeb:  String,
    officemarch:  String,
    officeapril:  String,
    officemay:  String,
    officejune:  String,
    officejuly:  String,
    officeaug:  String,
    officesep:  String,
    officeoct:  String,
    officenov:  String,
    officedec:  String,
    marketingCost:  String,	
    marketingjan:  String,
    marketingfeb:  String,
    marketingmarch:  String,
    marketingapril:  String,
    marketingmay:  String,
    marketingjune:  String,
    marketingjuly:  String,
    marketingaug:  String,
    marketingsep:  String,
    marketingoct:  String,
    marketingnov:  String,
    marketingdec:  String,
    events:  String,	
    eventsjan:  String,
    eventsfeb:  String,
    eventsmarch:  String,
    eventsapril:  String,
    eventsmay:  String,
    eventsjune:  String,
    eventsjuly:  String,
    eventsaug:  String,
    eventssep:  String,
    eventsoct:  String,
    eventsnov:  String,
    eventsdec:  String,
});

module.exports = Expenseform;
